### ISSUE TITLE
Bug:Crash of the Nikto Tests 

### ISSUE THREAD

**Issue by Mehmet112** [sullo/nikto#784]
### Expected behavior
Nikto tests completed successfully.
### Actual behavior
Nikto tests crashed.
### Steps to reproduce
When I set  Web Server “Permit Access only with HTTPS ” attiribute on my project , Nikto test is crashed.If I disabled this attiributes Nikto test execution was completed successfully.
 you can see log file.
[2022-12-29_082134_3884_task591_swcpu-oc2---tes_run.1035.285.10_3884.txt](https://github.com/sullo/nikto/files/10373170/2022-12-29_082134_3884_task591_swcpu-oc2---tes_run.1035.285.10_3884.txt)

### Nikto version
2.1.6

**Comment by sullo** [comment]
@Mehmet112 why did you close this one?

**Comment by Mehmet112** [comment]
I reopened again. Sorry for my mistake.

**Comment by sullo** [comment]
This appears to be an issue in whatever is calling nikto--some kind of python program. This error is from python, not perl
```
[2022-12-29 11:21:32.950159] [33m[1mWARNING[0m:  	Nikto terminated unexpectedly with the following return code: -13. (host: 172.255.30.253, port: 443)
[2022-12-29 11:21:32.951040] Traceback (most recent call last):
[2022-12-29 11:21:32.951190]   File "/home/siesta/nikto/output_fixer.py", line 65, in _remove_unparsable_chars
[2022-12-29 11:21:32.951447]     ElementTree.fromstring(data)
[2022-12-29 11:21:32.951697]   File "/usr/lib/python3.10/xml/etree/ElementTree.py", line 1345, in XML
[2022-12-29 11:21:32.952190]     return parser.close()
[2022-12-29 11:21:32.952398] xml.etree.ElementTree.ParseError: no element found: line 1, column 0
```
